package meter

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/andig/evcc/api"
)

func decorateLgess(base api.Meter, meterEnergy func() (float64, error), battery func() (float64, error)) api.Meter {
	switch {
	case battery == nil && meterEnergy == nil:
		return base

	case battery == nil && meterEnergy != nil:
		return &struct {
			api.Meter
			api.MeterEnergy
		}{
			Meter: base,
			MeterEnergy: &decorateLgessMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && meterEnergy == nil:
		return &struct {
			api.Meter
			api.Battery
		}{
			Meter: base,
			Battery: &decorateLgessBatteryImpl{
				battery: battery,
			},
		}

	case battery != nil && meterEnergy != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterEnergy
		}{
			Meter: base,
			Battery: &decorateLgessBatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decorateLgessMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}
	}

	return nil
}

type decorateLgessBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateLgessBatteryImpl) SoC() (float64, error) {
	return impl.battery()
}

type decorateLgessMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateLgessMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}
